package com.paic.nbm.analyticsservice.ProtocolBuilder;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.paic.nbm.analyticsservice.Entities.ConsolidatedDiagram;
import com.paic.nbm.analyticsservice.ExternalRequest.ExternalApi;
import com.paic.nbm.analyticsservice.Helper.FlowDiagramBuilder;
import com.paic.nbm.analyticsservice.PcapGenerator.PcapDownloaderInfo;
import com.paic.nbm.analyticsservice.PcapGenerator.SerializableController;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

@Slf4j
@Component("ALL")
public class ConsolidatedProtocolAnalytics {

    @Autowired
    ProtocolViewAnalytics protocolViewAnalytics;

    @Autowired
    SS7CAPAnalytics ss7CAPAnalytics;

    @Autowired
    SS7MAPAnalytics ss7MAPAnalytics;
    @Autowired
    SIPAnalytics sipAnalytics;

    @Autowired
    SMPPAnalytics smppAnalytics;

    @Autowired
    GTPAnalytics gtpAnalytics;

    @Autowired
    HTTPAnalytics httpAnalytics;

    @Autowired
    HTTPOCSAnalytics httpOcsAnalytics;

    @Autowired
    HTTPSS7Analytics httpSS7Analytics;

    @Autowired
    DiameterAnalytics diameterAnalytics;

    @Autowired
    ExternalApi externalApi;

    @Value("${records.page}")
    String recordsPerPage;

    @Value("${external.api.enable}")
    boolean externalApiEnable;

    @Value("${msisdn.prefixes}")
    String msisdnPrefixes;

    String[] prefixesArray = new String[]{};

    public static ConcurrentHashMap<String , Integer> resultQueryCount = new ConcurrentHashMap<>();
    public static ConcurrentHashMap<String , List<ConsolidatedDiagram>> resultDiagram = new ConcurrentHashMap<>();
    public static ConcurrentHashMap<String, PcapDownloaderInfo> pcapDataToDownload = new ConcurrentHashMap<>();
    Gson gson = new GsonBuilder().disableHtmlEscaping().create();

    //TODO: Both ways of obtaining the information will temporarily coexist. The information generated by v2 must be well validated before removing the v1
    public HashMap<String, Object> buildSequenceDiagramAll(HashMap<String, Object> parameters) {
        List<String> imsiList = new ArrayList<>();
        List<String> msisdnList = new ArrayList<>();
        String regex8length = "^(00972|0|972|\\+972|)[23489][0-9]{7}$";
        String regex9length = "^(00972|0|972|\\+972|)[57][0-9]{8}$";
        Pattern pattern8length = Pattern.compile(regex8length);
        Pattern pattern9length = Pattern.compile(regex9length);

        String imsi = (String) parameters.get("imsi");
        String msisdn = (String) parameters.get("msisdn");

        if (!imsi.isEmpty() && !imsi.equals("NA"))
            imsiList.add(imsi);
        if (!msisdn.isEmpty() && !msisdn.equals("NA"))
            msisdnList.add(msisdn);

        if (!(msisdnPrefixes == null || msisdnPrefixes.isEmpty()))
            prefixesArray = msisdnPrefixes.replace(" ", "").split(",");

        if (externalApiEnable) {
            if (!imsiList.isEmpty() && msisdnList.isEmpty()) {
                List<String> response = externalApi.getRequest(ExternalApi.TypeRequest.MSISDN, imsi);
                log.info("externalApi IMSI parameter {}, MSISDN response {}", imsi, response);
                if (response != null && !response.isEmpty())
                    msisdnList.addAll(response);
                if (!msisdnList.isEmpty() && msisdnList.get(0).length() == 12 && msisdnList.get(0).startsWith("972"))
                    msisdnList.set(0, msisdnList.get(0).substring(3));
            } else if (!msisdnList.isEmpty() && imsiList.isEmpty()) {
                List<String> response = externalApi.getRequest(ExternalApi.TypeRequest.IMSI, msisdnList.get(0));
                log.info("externalApi MSISDN parameter {}, IMSI response {}", msisdnList.get(0), response);
                // if the IMSI list is not empty and the first element starts with 425, this is a 019mobile MSISDN
                if (response != null && !response.isEmpty() && response.get(0).startsWith("425"))
                    imsiList.addAll(response);
            }
        }

        // Fill the MSISDN list with the prefixes configured concatenating the MSISDN in National format
        if (prefixesArray.length > 0 && !msisdnList.isEmpty()) {
            if (pattern8length.matcher(msisdnList.get(0)).matches()) {
                String finalMsisdn = msisdnList.get(0).substring(msisdnList.get(0).length() - 8);
                msisdnList.set(0, finalMsisdn);
                msisdnList.addAll(
                        Arrays.stream(prefixesArray).map(prefix -> prefix.trim() + finalMsisdn).collect(Collectors.toList())
                );
            } else if (pattern9length.matcher(msisdnList.get(0)).matches()) {
                String finalMsisdn = msisdnList.get(0).substring(msisdnList.get(0).length() - 9);
                msisdnList.set(0, finalMsisdn);
                msisdnList.addAll(
                        Arrays.stream(prefixesArray).map(prefix -> prefix.trim() + finalMsisdn).collect(Collectors.toList())
                );
            }
        }

        log.info("msisdnList {}", msisdnList);
        log.info("imsiList {}", imsiList);

        String startDate = (String) parameters.get("startDate");
        String endDate = (String) parameters.get("endDate");
        String timezone = (String) parameters.get("timezone");
        HashMap<String, Boolean> protocols = (HashMap<String, Boolean>) parameters.get("protocols");

        int page = 1;
        try {
            page = Integer.parseInt((String) parameters.get("page"));
        } catch (Exception e) {
            log.error("Error parsing page number: {}", e.getMessage());
        }

        resultQueryCount = new ConcurrentHashMap<>();
        resultDiagram = new ConcurrentHashMap<>();
        pcapDataToDownload = new ConcurrentHashMap<>();
        return build(startDate, endDate, timezone, imsiList, msisdnList, page, protocols);
    }

    public HashMap<String, Object> build(String startDate, String endDate, String timezone
            , List<String> imsi, List<String> msisdn, int page, HashMap<String, Boolean> protocols) {
        HashMap<String, Object> result = new HashMap<>();
        List<Integer> countResult = new ArrayList<>();
        int recordsPages = Integer.parseInt(recordsPerPage);
        int currentPage = Math.max(page, 1);
        result.put("currentPage", currentPage);
        result.put("recordsPerPage", recordsPages);

        HashMap<String, Object> filterGroupingCondition = protocolViewAnalytics.buildGroupingCondition(protocols, startDate, endDate, timezone, imsi, msisdn);

        WorkerProtocolThread workerProtocol = new WorkerProtocolThread(ss7CAPAnalytics, sipAnalytics, smppAnalytics,
                gtpAnalytics, httpAnalytics, diameterAnalytics,ss7MAPAnalytics, httpOcsAnalytics, httpSS7Analytics);
        workerProtocol.setProtocolViewAnalytics(protocolViewAnalytics);
        workerProtocol.setProtocols(protocols);
        workerProtocol.setProtocolValues("VIEW", filterGroupingCondition, "COUNT", timezone, currentPage, recordsPages);
        ExecutorService executor = Executors.newFixedThreadPool(1);
        executor.execute(workerProtocol);
        executor.shutdown();
        while (!executor.isTerminated()) {}

        for (var entry : resultQueryCount.entrySet()) {
            int pages = (int) Math.ceil(Double.parseDouble(entry.getValue().toString()) / recordsPages);
            countResult.add(pages);
        }

        int totalPages = 0;
        if(!countResult.isEmpty()) {
            totalPages = countResult.get(countResult.size() - 1);
            result.put("result", buildQuery(filterGroupingCondition, timezone, currentPage, recordsPages, protocols));
        } else {
            List<String> emptyList = new ArrayList<>();
            emptyList.add("Title: No records found\n");
            result.put("result", emptyList);
        }

        result.put("totalPages", totalPages);
        result.put("pcapData", SerializableController.encode(getListOfPcapDownloaderInfo()));
        return result;
    }

    public ArrayList<String> buildQuery(HashMap<String, Object> filters, String timezone, int page, int limit, HashMap<String, Boolean> protocols) {
        List<ConsolidatedDiagram> consolidatedDiagramList = new ArrayList<>();
        ExecutorService executor = Executors.newFixedThreadPool(1);
        WorkerProtocolThread workerProtocol = new WorkerProtocolThread(ss7CAPAnalytics, sipAnalytics, smppAnalytics,
            gtpAnalytics, httpAnalytics, diameterAnalytics,ss7MAPAnalytics, httpOcsAnalytics, httpSS7Analytics);
        workerProtocol.setProtocolViewAnalytics(protocolViewAnalytics);
        workerProtocol.setProtocols(protocols);
        workerProtocol.setProtocolValues("VIEW", filters, "PROTOCOL", timezone, page, limit);
        executor.execute(workerProtocol);
        executor.shutdown();

        while (!executor.isTerminated()) {}

        log.info("Finished thread Query. DiagramSize:{}", resultDiagram.size());
        for (var entry : resultDiagram.entrySet()) {
            consolidatedDiagramList.addAll(entry.getValue());
        }
        consolidatedDiagramList
            .sort(Comparator.comparing(ConsolidatedDiagram::getTimestampToOrder)
            .thenComparing(ConsolidatedDiagram::getUSecondsToOrder));
        return buildDiagram(consolidatedDiagramList);
    }

    private ArrayList<String> buildDiagram(List<ConsolidatedDiagram> list) {
        ArrayList<String> resultData = new ArrayList<>();
        ArrayList<String> rowData = new ArrayList<>();
        FlowDiagramBuilder flowDiagramBuilder = new FlowDiagramBuilder("Consolidated Diagram");
        list.forEach(item -> {
            rowData.add(item.getModal());
            switch (item.getProtocol()) {
                case "diameter":
                    flowDiagramBuilder.setTimestamp(item.getTimestamp());
                    flowDiagramBuilder.setFrom(item.getFrom());
                    flowDiagramBuilder.setTo(item.getTo());
                    flowDiagramBuilder.setSeparator(item.isSeparator()).setType("diameter_" + item.getType());
                    flowDiagramBuilder.buildEvent();
                    break;

                case "sip":
                    flowDiagramBuilder.setTimestamp(item.getTimestamp());
                    flowDiagramBuilder.setFrom(item.getFrom());
                    flowDiagramBuilder.setTo(item.getTo());
                    flowDiagramBuilder.setSeparator(true).setType("sip_" + item.getType());
                    flowDiagramBuilder.buildEvent();
                    break;

                case "smpp":
                    flowDiagramBuilder.setTimestamp(item.getTimestamp());
                    flowDiagramBuilder.setFrom(item.getFrom());
                    flowDiagramBuilder.setTo(item.getTo());
                    flowDiagramBuilder.setType("smpp_" + item.getType());
                    flowDiagramBuilder.setSeparator(item.isSeparator());
                    flowDiagramBuilder.buildEvent();
                    break;

                case "gtp":
                    flowDiagramBuilder.setTimestamp(item.getTimestamp());
                    flowDiagramBuilder.setFrom(item.getFrom());
                    flowDiagramBuilder.setTo(item.getTo());
                    flowDiagramBuilder.setSeparator(item.isSeparator()).setType("gtp_" + item.getType());
                    flowDiagramBuilder.buildEvent();
                    break;

                case "http":
                    flowDiagramBuilder.setTimestamp(item.getTimestamp());
                    flowDiagramBuilder.setFrom(item.getFrom());
                    flowDiagramBuilder.setTo(item.getTo());
                    flowDiagramBuilder.setSeparator(item.isSeparator()).setType("http_" + item.getType());
                    flowDiagramBuilder.buildEvent();
                    break;

                case "http-ss7":
                    flowDiagramBuilder.setTimestamp(item.getTimestamp());
                    flowDiagramBuilder.setFrom(item.getFrom());
                    flowDiagramBuilder.setTo(item.getTo());
                    flowDiagramBuilder.setSeparator(item.isSeparator()).setType("http-ss7_" + item.getType());
                    flowDiagramBuilder.buildEvent();
                    break;

                case "http-ocs":
                    flowDiagramBuilder.setTimestamp(item.getTimestamp());
                    flowDiagramBuilder.setFrom(item.getFrom());
                    flowDiagramBuilder.setTo(item.getTo());
                    flowDiagramBuilder.setSeparator(item.isSeparator()).setType("http-ocs_" + item.getType());
                    flowDiagramBuilder.buildEvent();
                    break;

                case "cap":
                    flowDiagramBuilder.setTimestamp(item.getTimestamp());
                    flowDiagramBuilder.setFrom(item.getFrom());
                    flowDiagramBuilder.setTo(item.getTo());
                    flowDiagramBuilder.setSeparator(item.isSeparator()).setType("cap_" + item.getType());
                    flowDiagramBuilder.buildEvent();
                    break;

                case "map":
                    flowDiagramBuilder.setTimestamp(item.getTimestamp());
                    flowDiagramBuilder.setFrom(item.getFrom());
                    flowDiagramBuilder.setTo(item.getTo());
                    flowDiagramBuilder.setSeparator(item.isSeparator()).setType("map_" + item.getType());
                    flowDiagramBuilder.buildEvent();
                    break;

            }
        });
        resultData.add(0, flowDiagramBuilder.buildSequenceDiagram());
        resultData.addAll(rowData);
        return resultData;
    }

    private String getListOfPcapDownloaderInfo() {
        List<PcapDownloaderInfo> pcapSlicesList = new ArrayList<>();
        pcapDataToDownload.keySet().forEach(key -> {
            PcapDownloaderInfo pePcapDownloaderInfo = pcapDataToDownload.get(key);
            pcapSlicesList.add(pePcapDownloaderInfo);
        });
        return gson.toJson(pcapSlicesList);
    }
}
