#Sequence Diagram builder and PCAP generation
server.port=9999

#Database connection
spring.datasource.url=jdbc:postgresql://172.31.42.89:5432/nbm
spring.datasource.username=nbm
spring.datasource.password=M$vCJu9LtnaT
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#ENABLE to print output of cmd executors in log
process.cmd.debug = true

external.api.enable=true
external.api.endpoint=https://paiclb.019mobile.co.il:8051/
external.api.timeout.connection=5000
external.api.timeout.read=30000

records.page=100
seconds.diff.trans = 30
msisdn.prefixes=0,972,+972,00972
merge.pcap.binary=/opt/paic/nbm-analytics/merge_pcaps
# tshark.separator possible values are: COMMA or SPACE
tshark.frames.separator=SPACE

logging.level.root=INFO
logging.file.name=/var/log/paic/nbm-analytics/analytics.log

# Maximum number of PCAP downloads allowed in parallel
max.allowed.downloads=3